# Generated by Django 4.1.3 on 2022-11-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_newsletter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
    ]
